version: '3.8'
services:
  nginx:
    image: 905418337664.dkr.ecr.eu-central-1.amazonaws.com/leitliniengpt_prod/nginx:latest
    ports:
      - "80:80" # Expose Nginx on port 80 to the host
    depends_on:
      - frontend
      - backend
  frontend:
    image: 905418337664.dkr.ecr.eu-central-1.amazonaws.com/leitliniengpt_prod/frontend:latest
    # Removed volumes section as it's not applicable for Elastic Beanstalk deployment
  backend:
    image: 905418337664.dkr.ecr.eu-central-1.amazonaws.com/leitliniengpt_prod/backend:latest
    # Removed volumes section as it's not applicable for Elastic Beanstalk deployment
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with file watching in some environments
      - HOST=0.0.0.0
    env_file:
      - KEYs.env  # Ensure this file is included in your Elastic Beanstalk deployment package
